### ISSUE TITLE
.git folder too big

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/MultiAssayExperiment#146] opened 2016-07-12 02:11 UTC
```
du -h MultiAssayExperiment
```
It's about 85 Mb in total usage. About 83 Mb are from the `.git` folder.

**Comment by LiNk-NY** [comment] 2016-07-12 15:48
Reopened #44

**Comment by lwaldron** [comment] 2016-07-13 15:36
I just now did a git pull that brought down almost as much:

$ du -hs .git
 77M	.git

**Comment by lwaldron** [comment] 2016-07-13 15:37
Duplicate of #44.

**Closed by lwaldron** 2016-07-13 15:37 UTC
Labels: duplicate

**Comment by LiNk-NY** [comment] 2016-07-13 15:40
@lwaldron What repo did you pull from? 
I applied the tool and it was reduced to <4Mb. I have worked on it since.
